version: '3.9'

services:
  nginx:
    build: ./nginx
    volumes:
      - static_volume:/usr/src/api_goods/staticfiles
    ports:
      - 1337:80
    depends_on:
      - api_goods
  api_goods:
    container_name: api_goods
    build: .
    command: gunicorn config.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - static_volume:/usr/src/api_goods/staticfiles
    expose:
      - 8000
    env_file:
      - ./local.env
    depends_on:
      - db
  db:
    container_name: api_goods_db
    image: postgres:13
    volumes:
      - ./postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
volumes:
  postgres_data:
  static_volume: